# Generated by Django 5.0.1 on 2024-07-10 06:37

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('industry_id', models.AutoField(primary_key=True, serialize=False)),
                ('industry_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobStatus',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('skill_id', models.AutoField(primary_key=True, serialize=False)),
                ('skill_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=100)),
                ('industry', models.ManyToManyField(to='jobposting.industry')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True, null=True)),
                ('founded_date', models.DateField(blank=True, null=True)),
                ('company_size', models.IntegerField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('description', models.TextField(blank=True, null=True)),
                ('industry', models.ManyToManyField(to='jobposting.industry')),
            ],
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=100)),
                ('job_position', models.CharField(max_length=100)),
                ('job_type', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('requirements', models.TextField(blank=True)),
                ('benefits', models.TextField(blank=True)),
                ('salary', models.IntegerField(blank=True, null=True)),
                ('location_type', models.CharField(choices=[('Onsite', 'Onsite'), ('Remote', 'Remote')], default='Onsite', max_length=20)),
                ('application_deadline', models.DateTimeField()),
                ('application_instructions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application_count', models.IntegerField(blank=True, default=0, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobposting.company')),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobposting.department')),
                ('industry_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobposting.industry')),
            ],
        ),
        migrations.CreateModel(
            name='JobStatusLog',
            fields=[
                ('joblog_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_changed', models.DateTimeField(auto_now_add=True)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobposting.jobposting')),
                ('status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobposting.jobstatus')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='jobposting.company')),
            ],
        ),
        migrations.AddField(
            model_name='jobposting',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobposting.location'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='skills',
            field=models.ManyToManyField(blank=True, to='jobposting.skill'),
        ),
    ]
