# Generated by Django 5.0.1 on 2024-07-10 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applicant', '0001_initial'),
        ('jobposting', '__first__'),
        ('recruiter', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationStatus',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False)),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('applicant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applicant.applicants')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobposting.company')),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobposting.jobposting')),
                ('referral_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.recruiters')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationStatusLog',
            fields=[
                ('applog_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_changed', models.DateTimeField(auto_now_add=True)),
                ('application_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.application')),
                ('status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.applicationstatus')),
            ],
        ),
    ]
