# Generated by Django 5.0.1 on 2024-07-10 06:37

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobposting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recruiters',
            fields=[
                ('recruiter_id', models.AutoField(primary_key=True, serialize=False)),
                ('gender', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField(null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('martial_status', models.CharField(max_length=30)),
                ('home_town', models.CharField(max_length=100)),
                ('permanent_address', models.CharField(max_length=255)),
                ('pincode', models.IntegerField()),
                ('current_location', models.CharField(max_length=400)),
                ('resume', models.FileField(upload_to='media/recruiter_resumes')),
                ('total_years_of_experience', models.PositiveIntegerField(blank=True, null=True)),
                ('languages', models.CharField(blank=True, max_length=255, null=True)),
                ('about', models.CharField(max_length=1000, null=True)),
                ('companies', models.ManyToManyField(to='jobposting.company')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecruiterExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('salary', models.IntegerField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('recruiter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='recruiter.recruiters')),
            ],
        ),
        migrations.CreateModel(
            name='RecruiterEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=100)),
                ('field_of_specialization', models.CharField(blank=True, max_length=200)),
                ('institute_name', models.CharField(max_length=200)),
                ('date_of_completion', models.DateField()),
                ('recruiter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='recruiter.recruiters')),
            ],
        ),
        migrations.CreateModel(
            name='RecruiterCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certification_name', models.CharField(max_length=100)),
                ('issuing_organization', models.CharField(max_length=100)),
                ('issue_date', models.DateField()),
                ('certifcate', models.FileField(blank=True, null=True, upload_to='media/recruiter_certificates')),
                ('recruiter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='recruiter.recruiters')),
            ],
        ),
        migrations.CreateModel(
            name='Recruiter_Specific_Job',
            fields=[
                ('recruiter_Specific_Job_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobposting.jobposting')),
                ('recruiter_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recruiter.recruiters')),
            ],
        ),
    ]
