# Generated by Django 5.0.1 on 2024-07-10 06:36

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobposting', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicants',
            fields=[
                ('applicant_id', models.AutoField(primary_key=True, serialize=False)),
                ('gender', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('martial_status', models.CharField(max_length=30)),
                ('home_town', models.CharField(max_length=100)),
                ('permanent_address', models.CharField(max_length=255)),
                ('pincode', models.IntegerField()),
                ('current_location', models.CharField(max_length=400)),
                ('resume', models.FileField(upload_to='media/applicant_resume')),
                ('preferred_job_type', models.CharField(max_length=100)),
                ('preferred_location', models.CharField(max_length=255)),
                ('total_years_of_experience', models.PositiveIntegerField(blank=True, null=True)),
                ('availability_to_join', models.CharField(max_length=20)),
                ('work_permit_for_USA', models.BooleanField(default=False)),
                ('languages', models.CharField(blank=True, max_length=255, null=True)),
                ('about', models.CharField(max_length=1000, null=True)),
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('interested_department', models.ManyToManyField(to='jobposting.department')),
                ('interested_industry', models.ManyToManyField(to='jobposting.industry')),
                ('skills', models.ManyToManyField(to='jobposting.skill')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicantInternship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('position_title', models.CharField(max_length=50)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('project_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('internship_certificate', models.FileField(blank=True, null=True, upload_to='media/applicant_internship')),
                ('applicant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internships', to='applicant.applicants')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicantExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('salary', models.IntegerField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobposting.department')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobposting.industry')),
                ('applicant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='applicant.applicants')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicantEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=100)),
                ('field_of_specialization', models.CharField(blank=True, max_length=200)),
                ('institute_name', models.CharField(max_length=200)),
                ('date_of_completion', models.DateField()),
                ('applicant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='applicant.applicants')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicantCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certification_name', models.CharField(max_length=100)),
                ('issuing_organization', models.CharField(max_length=100)),
                ('issue_date', models.DateField()),
                ('certifcate', models.FileField(blank=True, null=True, upload_to='media/applicant_certificates')),
                ('applicant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='applicant.applicants')),
            ],
        ),
    ]
